# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68a7f22283bf87a30cb92a9725726ab7be545dde7abd1b1eb526c36598cc33d726bcf6c7025d8864252e56272180b55abeef028d57c18ae93fc1692004a5ba14

test:
  secret_key_base: 61dedd0a91dd86c036cd7bd2fffd11717a01d6e6f503cddfa2960dc13226f2eba70eea42d2e0506f060fb490cdc2b9e2cb16a1f76d8ebfaf8787bb65bd0e2368

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
